mass_flow_rate = 8.10  # kg/s
compressor_pressure_ratio = 5.0
maximum_cycle_temperature = 1173.0  # K
thrust = 5096  # N
specific_fuel_consumption = 28.7  # kg/N-s
compressor_isentropic_efficiency = 0.80
compressor_outlet_total_temperature = 496.4  # K
combustion_chamber_pressure_loss = 0.05
combustion_chamber_efficiency = 0.99
gas_generator_isentropic_efficiency = 0.885
mechancial_efficiency, gas_generator_shaft_efficiency = 0.99, 0.99
inlet_stagnation_pressure = 101325  # Pa
inlet_stagnation_temperature = 288.15  # K
inlet_mach_number = 0.5
outlet_mach_number = 0.26
polytropic_efficiency = 0.89
number_of_stages = 5
rotational_speed = 25650  # rpm
inlet_hub_tip_ratio = 0.4
axial_channel = "COD"
